### ISSUE TITLE
Handle S3 buckets not in default region of us-east-1

### ISSUE THREAD

**Issue by whyrg** [ccnmtl/django-s3sign#31]
Entire library assumes bucket is in us-east-1.

**Comment by whyrg** [comment]
Since a boto client is passed in, this is instead implemented by the users of this library.

**Comment by whyrg** [comment]
Oops, turns out it's not really passed in but at: 
https://github.com/ccnmtl/django-s3sign/blob/master/s3sign/views.py#L49

**Comment by sdreher** [comment]
@whyrg - thanks for the issue report. Can you add a few more details about the change you're looking for? Thanks! Susan

**Comment by whyrg** [comment]
The boto3 client needs a [region_name parameter](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.client) passed in to specify the region that bucket was created under. This changes the URL that is ultimately generated by boto to communicate with AWS S3, as the default URL only works for us-east-1 S3 buckets.

This can default to `None` or `us-east-1`, but still needs to be exposed such that downstream users/applications (eg: mediathread) can utilize buckets in the same region as the application is deployed in.

**Comment by sdreher** [comment]
Thanks for the additional detail. We're putting together a fix for this.

**Comment by whyrg** [comment]
Writing to confirm this has done the trick!

For reference, using a bucket in the same region takes ~2 minutes for Django's `collectstatic` and `compress` process. Putting the bucket cross country (us-east-1 vs us-west-2) shot up the time taken to in excess of 20 minutes.
